/** English is the only supported application language. */
export const ENGLISH_COPY = {
    boot: 'Starting MHTalk...',
    connection: 'Call',
    startRoom: 'Start a private room',
    startRoomDesc: 'Create a room and send the code to your friend, or enter a room code you received. After joining, choose whether to enable the microphone or stay muted.',
    createRoom: 'Create Room',
    joinRoom: 'Join Room',
    waiting: 'Waiting for friends...',
    choosePeer: 'Select a friend from the circles above to view their screen share here',
    copyCode: 'Copy code',
    endCall: 'End call',
    stopVoice: 'Stop voice',
    startVoice: 'Start voice',
    muteMic: 'Mute mic',
    unmuteMic: 'Unmute mic',
    stopShare: 'Stop screen share',
    shareScreen: 'Share screen',
    refreshAudio: 'Refresh audio devices',
    screenQuality: 'Screen quality',
    screenFps: 'FPS',
    applySettings: 'Save / Apply',
    settingsSaved: 'Settings saved.',
    unsavedSettings: 'Unsaved changes',
    saveChat: 'Save chats locally',
    friendsInRoom: 'People in room',
    nobody: 'No one is connected yet.',
    showStream: 'Show stream',
    privateMessage: 'Private message',
    showProfile: 'Show Profile',
    profileUnavailable: 'This profile is no longer available.',
    profileBioUnavailable: 'No biography has been provided.',
    memberRole: 'Room role',
    memberId: 'Member ID',
    kickMember: 'Kick from room',
    kickConfirm: 'Do you want to kick this member from the room?',
    kickedOut: 'You were kicked from the room.',
    kickedMember: 'Member was kicked from the room.',
    ownerOnly: 'Only the room owner can use this option.',
    callVolume: 'Call volume',
    screenVolume: 'Screen volume',
    muteCall: 'Mute call sound',
    unmuteCall: 'Unmute call sound',
    muteScreen: 'Mute stream sound',
    unmuteScreen: 'Unmute stream sound',
    deleteRoomHistory: 'Delete room history',
    deleteAllLocalData: 'Delete all local data',
    reply: 'Reply',
    edit: 'Edit',
    edited: 'Edited',
    saveEdit: 'Save edit',
    cancel: 'Cancel',
    stopTransfer: 'Stop transfer',
    transferCanceled: 'Transfer canceled.',
    send: 'Send',
    writeMessage: 'Write a message...',
    privateTo: 'Private message to',
    replyTo: 'Replying to',
    editingMessage: 'Editing message',
    profileSettings: 'Edit profile',
    localAccount: 'Edit local account',
    name: 'Name',
    email: 'Email / Account',
    status: 'Status',
    bio: 'Bio',
    avatar: 'Avatar',
    profileImageTooLarge: 'Profile images must be smaller than 32MB.',
    banner: 'Banner',
    screenRecorder: 'Screen Recorder',
    screenRecorderTitle: 'Screen & Broadcast Recorder',
    screenRecorderHint: 'Record your current screen broadcast directly to your device with lightweight, adaptive settings.',
    screenRecorderIdle: 'Ready to record',
    screenRecorderStarting: 'Starting recorder…',
    screenRecorderRecording: 'Recording',
    screenRecorderPaused: 'Recording paused',
    screenRecorderStopping: 'Saving recording…',
    screenRecorderError: 'Recording error',
    screenRecorderQuality: 'Recording quality',
    screenRecorderQualityAdaptive: 'Adaptive to device',
    screenRecorderQualityHigh: 'High quality',
    screenRecorderQualityBalanced: 'Balanced',
    screenRecorderQualityPerformance: 'Performance saver',
    screenRecorderResolution: 'Recording resolution',
    screenRecorderResolutionAuto: 'Automatic (best for this device)',
    screenRecorderResolutionHint: 'Only resolutions supported by the captured screen are shown. Recording never upscales the source.',
    screenRecorderFps: 'Recording frame rate',
    screenRecorderFpsMatch: 'Match broadcast',
    screenRecorderCodec: 'Video codec',
    screenRecorderCodecAuto: 'Automatic (recommended)',
    screenRecorderIncludeAudio: 'Record broadcast audio',
    screenRecorderAutoStart: 'Start automatically with screen share',
    screenRecorderSource: 'Broadcast source',
    screenRecorderSourceUnavailable: 'Start screen sharing',
    screenRecorderEstimatedSize: 'Estimated size',
    screenRecorderAdaptiveEstimate: 'Calculated on start',
    screenRecorderStart: 'Start recording',
    screenRecorderPause: 'Pause',
    screenRecorderResume: 'Resume',
    screenRecorderStop: 'Stop and save',
    screenRecorderOpenFolder: 'Open recordings folder',
    screenRecorderSaveSettings: 'Save settings',
    screenRecorderSettingsSaved: 'Screen recorder settings saved.',
    screenRecorderNeedsStream: 'Start screen sharing before recording the broadcast.',
    screenRecorderSaved: 'Recording saved',
    screenRecorderSaveFailed: 'Could not record or save the broadcast',
    screenRecorderLocalOnly: 'Saved locally only',
    screenRecorderAudioUnavailable: 'The current broadcast has no audio track, so the video will be recorded without audio.',
    screenRecorderFile: 'Recording file',
    screenRecorderPlay: 'Play recording',
    screenRecorderPlaybackTitle: 'Saved recording',
    screenRecorderPlaybackHint: 'This is a normal local video with a seekable timeline after finalization.',
    screenRecorderPerformanceNote: 'The recorder reuses the current screen stream without starting a second capture and adapts frame rate and bitrate to reduce device load.',
    screenRecorderSettingsOnly: 'This window is only for recording settings. Start or stop recording from the button beside Screen Share.',
    screenRecorderToolbarStart: 'Start broadcast recording',
    screenRecorderToolbarStop: 'Stop recording and save MP4',
    screenRecorderArmed: 'Starting screen share and recording…',
    screenRecorderMp4Hint: 'When recording or screen sharing stops, capture closes first and is then converted automatically to MP4.',
    screenRecorderRepair: 'Repair interrupted recording',
    screenRecorderRepairTitle: 'Recover an incomplete recording',
    screenRecorderRepairHint: 'Continue the previous recording in a new safe segment, or stop it and repair the saved segments into an MP4 file.',
    screenRecorderNoRecovery: 'There are no incomplete recordings to repair.',
    screenRecorderResumePrevious: 'Continue previous recording',
    screenRecorderStopAndSaveMp4: 'Stop it and save MP4',
    screenRecorderRecoveryDate: 'Last saved',
    screenRecorderRecoverySize: 'Saved size',
    screenRecorderRecoverySegments: 'segments',
    screenRecorderRecoveryStarted: 'The previous recording is being continued.',
    screenRecorderRecoverySaved: 'Recording repaired and saved as MP4',
    screenRecorderRepairFailed: 'Could not repair the recording',
    screenRecorderFinalizingMp4: 'Preparing MP4…',
    screenRecorderDependencyPreparing: 'The MP4 converter is being prepared quietly in the background.',
    screenRecorderDependencyReady: 'The MP4 converter is ready.',
    screenRecorderDependencyFailed: 'The MP4 converter could not be prepared automatically.',
    recorderMyMic: 'My microphone',
    recorderMembers: 'Other members’ voices',
    recorderSystem: 'System / game audio',
    recorderAutoDuck: 'Automatically lower system audio while voices are active',
    recorderMicDevice: 'Recording microphone',
    recorderOutputDevice: 'Members’ output device',
    recorderMasterMeter: 'Final mix level',
    recorderMuteSource: 'Mute this source',
    recorderFinalizationSafe: 'A safe recording was saved immediately; MP4 is being prepared in the background.',
    fileActions: 'File actions',
    downloadToDesktop: 'Download to Desktop',
    saveAs: 'Save As',
    downloadProgress: 'Save progress',
    fileSaved: 'File saved',
    fileSaveFailed: 'Could not save file',
    overlayInteractive: 'Interactive mode',
    overlayClickThrough: 'Click-through mode',
    overlayMonitor: 'Monitor',
    overlayModeHotkey: 'Toggle chat overlay mode',
    overlayFullscreenLimit: 'Protected games and exclusive fullscreen may block overlays; use Borderless when needed.',
    overlayModeChanged: 'Overlay mode changed',
    notifications: 'Notifications',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit fullscreen',
    pip: 'PiP over apps',
    pipBackToApp: 'Remove PiP over apps',
    roomId: 'Room ID',
    mic: 'Microphone',
    speaker: 'Speaker / Headphones',
    defaultDevice: 'Default',
    lowInternet: 'Low Internet Mode',
    lowPc: 'Low PC Mode',
    audioOnlyHint: 'Audio only is enabled. Change screen quality if you want to share the screen.',
    micPermission: 'Could not start the microphone. Allow microphone access and try again.',
    screenPermission: 'Could not start screen sharing. Choose a screen/window that supports audio if you need video sound.',
    roomOpened: 'Room opened. Voice starts automatically when friends join.',
    micAutoStart: 'Allow microphone access to start voice automatically.',
    micJoinTitle: 'Turn on microphone?',
    micJoinDesc: 'Choose whether to enable your microphone now or stay muted in the room.',
    activateMicNow: 'Enable microphone',
    stayMuted: 'Stay muted',
    historyForNewMembers: 'Show previous messages to new members',
    historySyncedToNewMember: 'Previous messages were sent to the new member.',
    cameraWillStartWithStream: 'Camera will start automatically when screen sharing starts.',
    cameraNeedsStream: 'Camera with stream works only while screen sharing is active.',
    invalidRoom: 'Enter a valid room code like MHLKO-7K9A-X2QF',
    confirmEndCall: 'Are you sure you want to end the call?',
    confirmCloseApp: 'Are you sure you want to close the app?',
    chatDisconnected: 'Chat is not connected right now.',
    fileTypes: 'You can send images, videos, audio, and files up to 1GB.',
    sendingFile: 'Sending file...',
    fileFailed: 'Could not send the file. Chat is not connected.',
    retryAttachmentUnavailable: 'The original file is no longer available. Select it again to retry.',
    fileTooLarge: 'File is larger than the 1GB limit or cannot be sent safely.',
    fileSent: 'File sent.',
    voiceFailed: 'Could not send the voice message.',
    recordingStarted: 'Voice recording started. Press again to send.',
    recordingProblem: 'A problem happened while recording the voice message.',
    recordingDenied: 'Could not record audio. Make sure microphone access is allowed.',
    copied: 'Room code copied.',
    dataProblem: 'Could not start the local database. Restart the app.',
    chatCleared: 'This room history was deleted from this device.',
    confirmWipe: 'Do you want to delete all local data?',
    dataWiped: 'All local data deleted.',
    pipUnsupported: 'Picture in Picture is not supported on this device.',
    pipStartFirst: 'Start screen sharing first, then try PiP.',
    placeholderEmail: 'Optional',
    privateLabel: 'Private',
    mediaLabel: 'Media',
    fileLabel: 'File',
    emojiTitle: 'Emoji',
    attachTitle: 'Image/video/audio',
    voiceTitle: 'Voice message',
    ownerBadge: 'Room owner',
    me: 'Me',
    state_idle: 'Disconnected',
    state_connecting: 'Connecting',
    state_connected: 'Connected',
    state_room_ready: 'Room connected - waiting for members',
    state_peer_connecting: 'Connecting members',
    state_reconnecting: 'Reconnecting',
    state_disconnected: 'Disconnected',
    state_failed: 'Failed',
    typingOne: 'is typing...',
    typingMany: 'are typing...',
    error_bad_signal: 'Received an invalid signaling message.',
    error_signaling: 'Could not connect to signaling. Check your internet.',
    error_prepare_connection: 'Could not prepare the connection. Try again.',
    error_repair_connection: 'Could not repair the connection automatically. Try leaving and joining again.',
    error_data_channel: 'There is a problem with the chat channel.',
    error_bad_chat: 'Received an invalid chat message.',
    error_incomplete_file: 'The file arrived incomplete because of weak network.',
    minimizeTitle: 'Minimize to taskbar',
    maximizeTitle: 'Maximize/restore',
    trayTitle: 'Hide to system tray',
    deletedMessage: 'Message deleted',
    deleteMessage: 'Delete',
    confirmDeleteMessage: 'Delete this message?',
    sendQueued: 'Send selected images/files',
    pasteImage: 'Image added to send.',
    openImage: 'Open image',
    download: 'Download',
    log_info: 'Info',
    log_error: 'Error',
    privateP2PRoom: 'Private P2P Room',
    chatOverlayEmpty: 'Chat overlay',
    videoPreview: 'Video preview',
    dropFilesHere: 'Drop files here to add them to the send queue',
    attachmentQueued: 'File added to send queue.',
    bannedMembers: 'Banned members',
    unban: 'Allow return',
    noBannedMembers: 'No banned members.',
    settingsPanel: 'Settings',
    openSettings: 'Open settings',
    closeSettings: 'Close settings',
    screenAudioLimit: 'Note: excluding one app from full system audio needs OS/audio-driver support. Stream audio and call audio are separated inside the app as much as WebRTC allows.',
    closeTitle: 'Close',
    state_waiting_approval: 'Waiting for admin approval',
    joinRequests: 'Join requests',
    noJoinRequests: 'No requests right now.',
    approve: 'Approve',
    reject: 'Reject',
    joinAccepted: 'Join request approved.',
    joinRejected: 'Join request rejected.',
    promoteModerator: 'Make moderator',
    moderatorBadge: 'Moderator',
    promotedMember: 'Moderator role granted.',
    settingsButton: 'Settings',
    adminBadge: 'Admin',
    hotkeys: 'Hotkeys',
    voiceSettings: 'Voice',
    otherSettings: 'Others',
    configureHotkeys: 'Configure hotkeys',
    hotkeyTabHint: 'Configure global shortcuts and save them only after validation.',
    screenRecorderTabHint: 'Recording, quality, audio mixing, recovery, and saved recordings are managed separately here.',
    refreshDevices: 'Refresh devices',
    errorLog: 'Event log',
    noErrors: 'No errors recorded.',
    clearLog: 'Clear log',
    close: 'Close',
    pressHotkey: 'Press the shortcut now',
    clearHotkey: 'Clear shortcut',
    hotkeySaved: 'Hotkey saved and activated.',
    hotkeyDuplicate: 'This hotkey is already assigned',
    discardHotkeyChanges: 'Discard unsaved hotkey changes?',
    resetHotkeys: 'Reset to defaults',
    save: 'Save',
    muteMicHotkey: 'Mute/unmute mic',
    shareScreenHotkey: 'Start/stop screen share',
    endCallHotkey: 'End call',
    fullscreenHotkey: 'Fullscreen/restore stream',
    toggleSettingsHotkey: 'Open/close settings',
    holdVoiceHint: 'Hold to record, release to preview, then press Send.',
    voicePreview: 'Voice message ready to send',
    discardVoice: 'Delete recording',
    streamVolume: 'Stream sound',
    playScreenOn: 'Screen share started',
    playScreenOff: 'Screen share stopped',
    userJoined: 'A member joined',
    messageSending: 'Sending...',
    messageSent: 'Sent',
    messageDelivered: 'Delivered',
    messageSeen: 'Seen',
    troubleshootConnection: 'Troubleshoot connection',
    waitingApprovalTitle: 'Waiting for admin approval',
    waitingApprovalDesc: 'Your join request was sent. Stay here until an admin approves it.',
    restartConnectionStarted: 'Connection restarted without clearing messages.',
    restartWatchedStream: 'Restart stream',
    watchedStreamRestarted: 'Stream path is being restarted without leaving the room.',
    nativeVoiceEngine: 'Native Voice Engine',
    nativeVoiceEngineGroundwork: '0.8.5: Call audio runs in the isolated MHTalkVoice engine and is excluded from system broadcast audio.',
    echoGuardActive: 'Native echo guard is active: system-audio screen sharing excludes call audio without muting call members.',
    updateBootChecking: 'Checking for updates before opening the app...',
    updateAutoInstalling: 'A new update is available. Updating automatically...',
    checkUpdates: 'Check for updates',
    checkingUpdates: 'Checking for updates...',
    updateNone: 'No update available.',
    updateAvailable: 'Update available',
    updateInstall: 'Update now',
    updateInstalling: 'Downloading and installing update...',
    updateReady: 'Update installed. MHTalk will restart.',
    updateFailed: 'Update failed. Check GitHub Releases and latest.json setup.',
    updateTimeout: 'Update check timed out, continuing offline.',
    updateRetry: 'Retry',
    continueOffline: 'Continue Offline',
    updateProgress: 'Update progress',
    updateRequiredTitle: 'Required update available',
    updateRequiredDesc: 'You must update MHTalk before continuing. Press Update now and it will download, install, and restart automatically.',
    voiceSolutionsTitle: 'Native voice repair solutions',
    voiceSolutionsHint: 'Try Solution 1, then 2, then 3, then 4 during a call or mic test, then keep the best one for your device.',
    voiceSolutionApplied: 'Voice solution applied',
    voiceSolutionFailed: 'Could not apply voice solution',
    voiceEnhanceOn: 'Voice Enhance',
    voiceEnhanceOff: 'Turn off Voice Enhance',
    voiceEnhanceEnabled: 'Voice Enhance enabled',
    voiceEnhanceDisabled: 'Voice Enhance off',
    voiceEnhanceHint: 'Enables native voice boost, clarity, compressor and limiter for member audio. Turn it off if a device has trouble; the base Native voice path stays unchanged.',
    micTest: 'Mic test',
    micTestStart: 'Start mic test',
    micTestStop: 'Stop mic test',
    micTestHint: 'You will hear your mic through the selected speaker. Headphones are recommended to avoid echo.',
    micTestFailed: 'Could not start mic test. Check mic permission and selected device.',
    micLevel: 'Mic level',
    closeStream: 'Close stream',
    downloadLog: 'Download TXT log',
    logDownloaded: 'Event log downloaded.',
    streamStarted: 'Screen stream started.',
    streamEnded: 'Screen stream ended.',
    liveBadge: 'LIVE',
    openFile: 'Open file',
    status_sending: 'Sending',
    status_queued: 'Queued',
    status_preparing: 'Preparing',
    'status_awaiting-delivery': 'Waiting for recipient confirmation',
    status_receiving: 'Receiving',
    status_retrying: 'Retrying',
    status_completed: 'Completed',
    status_failed: 'Failed',
    status_canceled: 'Canceled',
    retry: 'Retry',
    youtubeVideo: 'YouTube video',
    originalMessageMissing: 'Original message is not in this history.',
    openStream: 'Open Stream',
    switchStream: 'Switch Stream',
    watchingStream: 'Watching',
    streamStopped: 'Stream stopped',
    muteAllMembers: 'Mute All Members',
    unmuteAllMembers: 'Unmute All Members',
    raiseHand: 'Raise Hand',
    requestToSpeak: 'Request to speak',
    requestedPermissionToSpeak: 'Requested permission to speak',
    allowToSpeak: 'Allow to speak',
    rejectSpeakRequest: 'Reject request',
    speakRequestCooldown: 'You can request permission every 15 seconds',
    adminAllowedSpeak: 'Admin allowed member to speak',
    adminRejectedSpeak: 'Admin rejected the speak request',
    clearVoicePriority: 'Clear Voice Priority',
    mutedByAdmin: 'Muted by admin',
    memberMutedByAdmin: 'Muted by admin',
    muteForEveryone: 'Mute for everyone',
    unmuteForEveryone: 'Unmute for everyone',
    showChatOverlay: 'Show Chat Overlay',
    hideChatOverlay: 'Hide Chat Overlay',
    voiceAutoQuality: 'Voice Auto Quality',
    streamAutoQuality: 'Stream Auto Quality',
    networkWeakAdapting: 'Network weak, adapting quality',
    streamQualityLimitedNetwork: 'Stream quality limited by network',
    streamQualityLimitedDevice: 'Stream quality limited by device',
    streamViewerClosed: 'Stream viewer panel closed',
    streamViewerOpened: 'Stream viewer panel opened',
    voiceProfileChanged: 'Voice profile changed',
    adminMutedAll: 'Admin muted all members',
    chatOverlayShown: 'Chat overlay shown',
    chatOverlayHidden: 'Chat overlay hidden',
    waitingForMembers: 'Waiting for members',
    roomReady: 'Room ready',
    autoMaxQuality: 'Auto Max for your display and network',
    audioOnly: 'Audio only',
    chatOverlayCustomize: 'Customize Chat Overlay',
    overlayEditorTitle: 'Chat Overlay Editor',
    overlayEditorHint: 'This area simulates your screen. Drag and resize the overlay box and tune its appearance.',
    overlayOpacity: 'Overlay opacity',
    overlayBorderRadius: 'Overlay corners',
    overlayShowText: 'Show text messages',
    overlayShowImages: 'Show images and media',
    overlayShowAudio: 'Show voice/audio messages',
    overlayReset: 'Reset overlay',
    moveControls: 'Position and proportional size',
    moveUp: 'Move up',
    moveDown: 'Move down',
    moveLeft: 'Move left',
    moveRight: 'Move right',
    enlargeTopRight: 'Enlarge toward the top-right',
    cameraCustomizationControls: 'Camera customization controls',
    chatCustomizationControls: 'Chat customization controls',
    cameraCropEdges: 'Crop camera edges',
    cropTop: 'Top',
    cropRight: 'Right',
    cropBottom: 'Bottom',
    cropLeft: 'Left',
    camera: 'Camera',
    cameraSource: 'Camera source',
    cameraToggle: 'Toggle camera',
    cameraUnavailable: 'Camera is unavailable or permission was denied.',
    cameraMirror: 'Mirror camera preview',
    cameraOverlayHint: 'Drag and resize the camera window inside the stream.',
    voicePriorityMax: 'Maximum Voice Priority',
    voicePriorityMaxHint: 'Under pressure, stream, camera, and overlay load are reduced before voice is affected.',
    cameraSettings: 'Camera Settings',
    cameraModeTitle: 'Choose camera mode',
    cameraModeHint: 'Choose whether to show camera alone in the stream area or together with screen sharing.',
    cameraWithStream: 'Camera with stream',
    cameraOnlyMode: 'Camera only',
    cameraModeBack: 'Back',
    cameraOverlayCustomize: 'Customize Camera Position',
    cameraFitMode: 'Camera framing',
    cameraFitCover: 'Fill frame with crop',
    cameraFitContain: 'Show full camera',
    cameraCropX: 'Horizontal crop focus',
    cameraCropY: 'Vertical crop focus',
    cameraOpacity: 'Camera opacity',
    cameraEditorTitle: 'Camera Box Editor',
    cameraEditorHint: 'Place and resize the camera box inside the stream area.',
    cameraEditMode: 'Camera editing mode',
    cameraResizeMode: 'Resize',
    cameraCropMode: 'Crop',
    cameraResizeModeHint: 'Drag the camera to move it. Hold and drag any arrow on its edges or corners to resize it.',
    cameraCropModeHint: 'Crop mode is active. The edge arrows are red; hold and drag them to hide unwanted parts of the camera image.',
    cameraCropping: 'Cropping camera edges',
    cameraDragHint: 'Drag to move · use edge arrows to resize',
    restoreOriginal: 'Restore original',
    cameraStart: 'Start Camera',
    cameraStop: 'Stop Camera',
    cameraOnly: 'Camera only',
    viewCamera: 'Watch camera',
    viewStream: 'Watch stream',
    viewStreamOrCamera: 'Choose what to watch',
    overlayPersisted: 'Overlay customization saved.',
    attachmentReady: 'File is ready. Press Enter or Send to upload.',
    attachmentRejected: 'This file cannot be sent.',
    mediaCheckPassed: 'Quick file check passed.',
    logInfo: 'Info',
    mediaDownloadToDesktop: 'Download to Desktop',
    mediaCopy: 'Copy',
    mediaSavedToDesktop: 'Media saved to Desktop.',
    mediaCopied: 'Media copied.',
    mediaCopyFailed: 'Could not copy media.',
    mediaDownloadFailed: 'Could not download media.',
    previewMyMedia: 'Preview my stream/camera',
    myMediaPreview: 'My stream and camera preview',
    myScreenPreview: 'Screen stream preview',
    myCameraPreview: 'Camera preview',
    myAudioPreview: 'Audio test',
    noSelfMediaPreview: 'Start screen sharing or camera to show the preview.',
    localScreenPreviewHint: 'This is a local preview of the current screen stream.',
    videoAttachment: 'Video',
    openVideo: 'Play video',
    mediaContextTitle: 'Media options',
    friendFallback: 'Friend',
    typingSeparator: ' and ',
  } as const;

export type EnglishCopyKey = keyof typeof ENGLISH_COPY;
