name = "mhtalk-token-service"
main = "src/index.ts"
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

[vars]
LIVEKIT_URL = "https://mhtalkremake-utuei6i7.livekit.cloud"

[[kv_namespaces]]
binding = "PRIVATE_ROOMS"
id = "3ced063544014961bd3aa2b5af26db09"
